export const ADD_MESSAGE_REQUEST = "ADD_MESSAGE_BEGIN";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAIL = "ADD_MESSAGE_FAIL";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_BEGIN";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
